[project]
name = "my-awesome-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "takvam", email = "alexander8921@hotmail.no" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
my-awesome-project = "my_awesome_project:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
