[project]
name = "my-awesome-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "takvam", email = "alexander8921@hotmail.no" }
]
requires-python = ">=3.14"
dependencies = [
    "ddgs>=9.16.0",
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-anthropic>=1.7.1",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.0",
    "numpy>=2.5.2",
    "openai>=3.6.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "wikipedia>=1.4.0",
]

[project.scripts]
my-awesome-project = "my_awesome_project:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
