name: Scheduled AI Agent

on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows you to also trigger it manually

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Sett opp uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Installer avhengigheter
        run: uv sync --frozen

 #     - name: Install dependencies
 #       run: pip install openai python-dotenv langchain-openai langchain-anthropic langchain_classic langchain_community duckduckgo-search

      - name: Run AI Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Stored in GitHub Secrets
        run: echo "What can i help you find in regards to fashion " | uv run python main.py
